dependencies {
    implementation(project(":HoTT-Report-XML"))
    implementation(project(":HoTT-Report-HTML"))
    implementation(project(":HoTT-Decoder"))
    implementation(project(":HoTT-Model"))
    implementation(project(":HoTT-Serial"))
    runtimeOnly(project(":jSerialCommPort"))
    implementation(project(":HoTT-TTS"))
    implementation(project(":HoTT-Voice"))
    implementation(project(":HoTT-UI"))
    implementation(project(":HoTT-Util"))
    implementation(project(":FirmwareUpdater"))
    runtimeOnly("com.fazecast:jSerialComm:_")
    implementation("org.apache.commons:commons-math3:_")
    runtimeOnly("org.freemarker:freemarker:_")
    implementation("commons-net:commons-net:_")
}
