@REM Script to build Windows install packages using jpackage of Java 17
@IF "%~1"=="" (
	@echo usage: CreateInstaller "0.9.4.1400"
	@GOTO end 
)
SET VERSION=%~1
jpackage --input FirmwareUpdater\build\libs --dest ..\release --name "FirmwareUpdater" --main-jar FirmwareUpdater-%VERSION%-win.jar --main-class "de.treichels.hott.update.FirmwareUpdaterKt"  --icon FirmwareUpdater\icon.ico --app-version %VERSION% --type msi --win-menu --win-menu-group "Graupner HoTT Tools" --win-shortcut --win-shortcut-prompt --vendor "Graupner" --win-dir-chooser --win-per-user-install
jpackage --input mz-16_mz-32_mc-32ex_Downloader\build\libs --dest ..\release --name "mz-16_mz-32_mc-32ex_Downloader" --main-jar mz-16_mz-32_mc-32ex_Downloader-%VERSION%-win.jar --main-class "de.treichels.hott.mz32.Mz32DownloaderKt"  --icon mz-16_mz-32_mc-32ex_Downloader\icon.ico --app-version %VERSION% --type msi --win-menu --win-menu-group "Graupner HoTT Tools" --win-shortcut --win-shortcut-prompt --vendor "Graupner" --win-dir-chooser --win-per-user-install
jpackage --input HoTT-TTS\build\libs --dest ..\release --name "HoTT-TTS" --main-jar HoTT-TTS-%VERSION%-win.jar --main-class "de.treichels.hott.tts.SpeechDialogKt"  --icon HoTT-TTS\icon.ico --app-version %VERSION% --type msi --win-menu --win-menu-group "Graupner HoTT Tools" --win-shortcut --win-shortcut-prompt --vendor "Graupner" --win-dir-chooser --win-per-user-install
jpackage --input VDFEditor\build\libs --dest ..\release --name "VDFEditor" --main-jar VDFEditor-%VERSION%-win.jar --main-class "de.treichels.hott.vdfeditor.ui.VDFEditorKt"  --icon VDFEditor\icon.ico --app-version %VERSION% --type msi --win-menu --win-menu-group "Graupner HoTT Tools" --win-shortcut --win-shortcut-prompt --vendor "Graupner" --win-dir-chooser --win-per-user-install
jpackage --input MDLViewer\build\libs --dest ..\release --name "MDLViewer" --main-jar MDLViewer-%VERSION%-win.jar --main-class "de.treichels.hott.mdlviewer.javafx.MdlViewerKt"  --icon MDLViewer\icon.ico --app-version %VERSION% --type msi --win-menu --win-menu-group "Graupner HoTT Tools" --win-shortcut --win-shortcut-prompt --vendor "Graupner" --win-dir-chooser --win-per-user-install
jpackage --input lzma-compress\build\libs --dest ..\release --name "lzma-compress" --main-jar lzma-compress-%VERSION%-win.jar --main-class "de.treichels.hott.lzma.LzmaCompressKt"  --icon lzma-compress\icon.ico --app-version %VERSION% --type msi --win-menu --win-menu-group "Graupner HoTT Tools" --win-shortcut --win-shortcut-prompt --vendor "Graupner" --win-dir-chooser --win-per-user-install
:end