[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="phase.brakeElevatorCurve" type="de.treichels.hott.model.Curve" --]
[#-- @ftlvariable name="phase.brakeMixer" type="de.treichels.hott.model.WingedMixer" --]
[#-- @ftlvariable name="phase.multiFlapMixer" type="de.treichels.hott.model.WingedMixer" --]
[#-- @ftlvariable name="phase.wingMixer" type="de.treichels.hott.model.WingedMixer" --]
[#-- @ftlvariable name="model.varioToneSensor" type="de.treichels.hott.model.enums.VarioToneSensor" --]
[#-- @ftlvariable name="phase.helicopterTrim" type="de.treichels.hott.model.HelicopterTrim" --]
[#-- @ftlvariable name="phase.wingTrim" type="de.treichels.hott.model.WingedTrim" --]
[#-- @ftlvariable name="control.controlSwitch" type="de.treichels.hott.model.ControlSwitch" --]
[#-- @ftlvariable name="mixer.YOffset" type="java.lang.Number" --]
[#-- @ftlvariable name="mixer.XOffset" type="java.lang.Number" --]
[#-- @ftlvariable name="mixer.travelHigh" type="java.lang.Number" --]
[#-- @ftlvariable name="mixer.travelLow" type="java.lang.Number" --]
[#-- @ftlvariable name="phase.gyroGain" type="java.lang.Number" --]
[#-- @ftlvariable name="phase.gyroSuppression" type="java.lang.Number" --]
[#-- @ftlvariable name="phase.helicopterMixer" type="de.treichels.hott.model.HelicopterMixer" --]
[#-- @ftlvariable name="mixer.curve" type="de.treichels.hott.model.Curve" --]
[#-- @ftlvariable name="png" type="de.treichels.hott.report.html.CurveImageGenerator" --]
[#-- @ftlvariable name="hex" type="de.treichels.hott.report.html.FreeMarkerHexConverter" --]
[#-- @ftlvariable name="model" type="de.treichels.hott.model.BaseModel" --]
[#-- @ftlvariable name="helicopterModel" type="de.treichels.hott.model.HelicopterModel" --]
[#-- @ftlvariable name="wingedModel" type="de.treichels.hott.model.WingedModel" --]
[#include 'de/treichels/hott/report/html/templates/hott/macros.ftl']
